In [2]:
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


np.random.seed(0)
n = 15
x = np.linspace(0,10,n) + np.random.randn(n)/5
y = np.sin(x)+x/6 + np.random.randn(n)/10

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=0)

def part1_scatter():
    %matplotlib notebook
    plt.figure()
    plt.scatter(X_train, y_train, label='training data')
    plt.scatter(X_test, y_test, label='test data')
    plt.legend(loc=4);

In [3]:
def answer_one():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures


    results = np.zeros([4,100])

    X_predict = np.linspace(0,10,100).reshape(-1,1)


    count = 0
    
    for i in [1,3,6,9]:
        
        poly = PolynomialFeatures(degree=i)

        X_train_poly = poly.fit_transform(X_train.reshape(-1, 1))
        
        X_predict_poly = poly.fit_transform(X_predict)

        linreg = LinearRegression().fit(X_train_poly, y_train)

        tmp_ans = linreg.predict(X_predict_poly).reshape(1,-1)
    
        results[count,:] = tmp_ans
        
        count = count + 1
    answer = results  
    return answer

answer_one()

array([[ 2.53040195e-01,  2.69201547e-01,  2.85362899e-01,
         3.01524251e-01,  3.17685603e-01,  3.33846955e-01,
         3.50008306e-01,  3.66169658e-01,  3.82331010e-01,
         3.98492362e-01,  4.14653714e-01,  4.30815066e-01,
         4.46976417e-01,  4.63137769e-01,  4.79299121e-01,
         4.95460473e-01,  5.11621825e-01,  5.27783177e-01,
         5.43944529e-01,  5.60105880e-01,  5.76267232e-01,
         5.92428584e-01,  6.08589936e-01,  6.24751288e-01,
         6.40912640e-01,  6.57073992e-01,  6.73235343e-01,
         6.89396695e-01,  7.05558047e-01,  7.21719399e-01,
         7.37880751e-01,  7.54042103e-01,  7.70203454e-01,
         7.86364806e-01,  8.02526158e-01,  8.18687510e-01,
         8.34848862e-01,  8.51010214e-01,  8.67171566e-01,
         8.83332917e-01,  8.99494269e-01,  9.15655621e-01,
         9.31816973e-01,  9.47978325e-01,  9.64139677e-01,
         9.80301028e-01,  9.96462380e-01,  1.01262373e+00,
         1.02878508e+00,  1.04494644e+00,  1.06110779e+0

In [4]:
def answer_two():
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.metrics.regression import r2_score

    # Your code here
    results_train = np.zeros([10, 1])
    results_test = np.zeros([10, 1])

    
    for i in range(0,10):
        
        poly = PolynomialFeatures(degree=i)

        X_train_poly = poly.fit_transform(X_train.reshape(-1, 1))
        
        X_test_poly = poly.fit_transform(X_test.reshape(-1, 1))

        linreg = LinearRegression().fit(X_train_poly, y_train)

        score_train = r2_score( y_train,linreg.predict(X_train_poly))
        
        score_test = r2_score( y_test,linreg.predict(X_test_poly))
        
        results_train[i] = score_train
        
        results_test[i] = score_test
        
        results_train = results_train.flatten()
        
        results_test = results_test.flatten()
    
    answer = (results_train, results_test)

    return (results_train, results_test)

answer_two()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:143: FutureWarning: The sklearn.metrics.regression module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


(array([0.        , 0.42924578, 0.4510998 , 0.58719954, 0.91941945,
        0.97578641, 0.99018233, 0.99352509, 0.99637545, 0.99803706]),
 array([-0.47808642, -0.45237104, -0.06856984,  0.00533105,  0.73004943,
         0.87708301,  0.9214094 ,  0.92021504,  0.6324795 , -0.64524777]))

In [ ]:
def answer_four():
    from sklearn.preprocessing import PolynomialFeatures
    from sklearn.linear_model import Lasso, LinearRegression
    from sklearn.metrics.regression import r2_score

    # Your code here
    poly = PolynomialFeatures(degree=12)

    X_train_poly = poly.fit_transform(X_train.reshape(-1, 1))

    X_test_poly = poly.fit_transform(X_test.reshape(-1, 1))

    linreg = LinearRegression().fit(X_train_poly, y_train)
    
    linlasso = Lasso(alpha=0.01, max_iter = 10000).fit(X_train_poly, y_train)

    score_linreg_test = linreg.score(X_test_poly, y_test)

    score_lasso_test = linlasso.score(X_test_poly, y_test)

    return (score_linreg_test, score_lasso_test)

# answer_four()